# Generated by Django 5.2.17 on 2026-09-02 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilityProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar (DZD)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='DZD', max_length=10)),
                ('project_duration_years', models.PositiveIntegerField(default=5, help_text='Duration of project evaluation in years')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Discount rate % (WACC/Target Return)', max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, help_text='Corporate income tax rate %', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='e.g., Equipment, Real Estate, Working Capital, Licensing', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lifespan_years', models.PositiveIntegerField(default=5, help_text='Asset useful life for depreciation calculations')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capex_items', to='projects.feasibilityproject')),
            ],
        ),
        migrations.CreateModel(
            name='OpexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='e.g., Salaries, Utilities, Marketing, Maintenance', max_length=100)),
                ('yearly_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual cost inflation rate %', max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opex_items', to='projects.feasibilityproject')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('yearly_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Annual revenue growth rate %', max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_streams', to='projects.feasibilityproject')),
            ],
        ),
    ]
